name: Bookstore API Automation

on:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

  schedule:
    # simulate running scheduler
    - cron: '0 18 * * *'

env:
  CI: true

jobs:

  api-test:

    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Allure CLI
        run: |
            sudo apt update
            sudo apt install -y allure
            
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
            sudo apt update
            sudo apt install -y default-jre
            curl -o allure.tgz -OL https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
            sudo tar -zxvf allure.tgz -C /opt/
            sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
            allure --version

      - name: Execute API Tests
        run: |
            pytest

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate \
          reports/allure-results \
          -o reports/allure-report \
          --clean

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-allure-report
          path: reports/allure-report

      - name: Upload API Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-logs
          path: reports/logs